[package]
name = "rusty"
version = "0.6.0"
authors = ["Douglas Luman <dluman@douglasjluman.com>"]
edition = "2021"
description = "Idiomatic Rust bindings for the spaCy Python NLP library"
repository = "https://github.com/dluman/rusTy.git"
readme = "README.md"
license = "CC0-1.0"
keywords = ["spacy", "nlp", "python", "pyo3", "bindings"]
categories = ["api-bindings", "text-processing"]

[dependencies]
pyo3 = { version = "0.21", features = ["abi3-py38", "auto-initialize"] }
numpy = "0.21"
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
